### ISSUE TITLE
?onfail=cache says there's no results, even though I was getting new results recently.

### ISSUE THREAD

**Issue by Lugghawk** [avwx-rest/AVWX-API#17]
One of my lookups for the OMAA ICAO responded with this error:

`https://avwx.rest/api/metar/omaa`

> "Report Lookup Error: Unable to fetch report from NOAA. You might wish to use '?onfail=cache' to return the most recent report even if it's not up-to-date"

A few minutes prior to the lookup that caused this, I had been getting metar information just fine. I decided to add the `?onfail=cache` to the request, since I'd rather get some out of date info instead of no info, and then I got this response:

`https://avwx.rest/api/metar/omaa?onfail=cache`

> "No report or cache was found for the requested station"

Something seems odd because I had been getting responses back previously. Unless the cache got dropped for some reason, or I'm misunderstanding the feature.

**Comment by flyinactor91** [comment]
I’ve noticed that the NOAA servers have been unpredictable lately. However, the cache option should still return data if available. I need to check if there’s a TTL on the cache table.

As for the NOAA issue, there’s not much I can do if their servers go down, but I can add more regional data sources to lessen the lid on NOAA. Is there a best source for UAE airports?

**Comment by Lugghawk** [comment]
I'm not sure unfortunately, we've only been using AVWX for these and not any other services.

I'm not too worried about issues with the source, I understand there's not much you can do on your end about them. I just wanted to bring the `onfail` issue up since it doesn't behave as expected.

**Comment by Lugghawk** [comment]
So I checked out the code here: https://github.com/avwx-rest/AVWX-API/blob/3c58312abe7175793f32c3dff1a3be469e298da7/avwx_api/handle/metar.py#L62 for the METAR handling which I'm using. 

It looks like the initial lookup is done via the cache too. I'm not sure if the `nofail=cache` makes sense in this context then, since if the initial check doesn't give you a valid return then we would not expect one the next time we check the cache. If anything appears in between the first and second calls, then it would be new data.

I'm not sure what to suggest to improve this. It's not clear from this block of code (and I'm not great at python) where the cache is being set from, but the second cache lookup on line 84 when nofail is specified seems redundant and won't actually come up with the older data.

**Comment by flyinactor91** [comment]
I found a bug where the second call to the cache was not forcing the data to be returned. I've refactored the code to force the cache to return on the first call and keep it in memory during handling removing the second call. The fix has been pushed. I've also changed the default onfail value to "cache"
