### ISSUE TITLE
Authorization Token requirements testing.

### ISSUE THREAD

**Issue by Lugghawk** [avwx-rest/AVWX-API#19]
Good day,

I noticed as per your blog post that come Nov 1st, there will be a mandatory authorization token required for all requests (even Hobby level).

I've made changes to my clients to allow for this, but it's not clear if its being done correctly. Even when including a phony token I'm still getting 200s from my requests. I am worried that, since I can't test my implementation with the token, that I might have an interruption on Nov 1st.

Is there something that I can do to ensure that my requests are conforming to the new requirements ahead of the switchover?

**Comment by Lugghawk** [comment]
Nevermind, I had been ignoring most of the response while doing my testing, and I just noticed that the "meta.note" in the response body disappears with a valid token.

**Comment by flyinactor91** [comment]
If there is no token or an invalid token in your request, there should be a note included in the response at data.meta.note saying that tokens will be required. If a token is given and is authenticated correctly, this note will not appear.
