### ISSUE TITLE
TAF - Different time formats

### ISSUE THREAD

**Issue by studio-jw** [avwx-rest/avwx-api#22]
## Expectation
`start_time.dt` and `end_time.dt` is always formatted in the correct [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)

## Result
The format differs from location to location.

### EBBR
_https://avwx.rest/api/taf/EBBR_

**Raw TAF**: `EBBR 050501Z 0506/0612 06011KT CAVOK`
```json
"start_time": {
  "repr": "0506",
  "dt": "2020-05-05T06:00:00+00:00Z"
}
```

### ELLX
_https://avwx.rest/api/taf/ELLX_

**Raw TAF**: `ELLX 050500Z 0506/0612 04010KT CAVOK`
```json
"start_time": {
  "repr": "0506",
  "dt": "2020-05-05T06:00:00Z"
}
```

It becomes especially difficult when this time has to be parsed for different weather stations. Tools like [Moment.js](https://momentjs.com/) fail.

Furthermore, the notation for EBBR does not appear to be correct. The letter "Z" should never be added when using "+00:00".

<img width="265" alt="Schermafbeelding 2020-05-05 om 08 20 11" src="https://user-images.githubusercontent.com/33237012/81039427-47984480-8ea9-11ea-86a5-3d36a9d69a82.png">

**Comment by flyinactor91** [comment]
I will need to add some more tests in the core library to figure out what is causing some date time objects to be created without a timezone, but I've made a change to the JSON formatter that should fix this problem's symptom for the end-user.

https://github.com/avwx-rest/avwx-api-core/commit/779cffd4826e43d12c0bf1e0fb43dca5d43c361a
